# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15.1
FROM ghcr.io/daemonless/base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="openjdk17-jre"
ARG UBOOQUITY_VERSION="3.1.0"
ARG UPSTREAM_URL="https://api.github.com/repos/linuxserver/docker-ubooquity/releases/latest"
ARG HEALTHCHECK_ENDPOINT="http://localhost:2202/"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

LABEL org.opencontainers.image.title="Ubooquity" \
      org.opencontainers.image.description="Free, lightweight home server for your comics and ebooks (EPUB, MOBI, PDF, CBZ, CBR) with OPDS support and a web reader." \
      org.opencontainers.image.source="https://github.com/daemonless/ubooquity" \
      org.opencontainers.image.url="https://vaemendis.net/ubooquity/" \
      org.opencontainers.image.documentation="https://vaemendis.net/ubooquity/static2/documentation" \
      org.opencontainers.image.licenses="LicenseRef-Ubooquity" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Media Servers" \
      io.daemonless.port="2202" \
      io.daemonless.volumes="/config,/books,/comics,/files" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.packages="${PACKAGES}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq='.tag_name | sub("-ls[0-9]+$"; "")' \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}"

# Install runtime dependencies
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Download and extract Ubooquity
RUN mkdir -p /app/ubooquity && \
    fetch -qo /tmp/ubooquity.zip "https://vaemendis.net/ubooquity/downloads/Ubooquity-${UBOOQUITY_VERSION}.zip" && \
    tar -xf /tmp/ubooquity.zip -C /app/ubooquity && \
    rm /tmp/ubooquity.zip

# The version actually downloaded above, not upstream's latest
RUN echo "${UBOOQUITY_VERSION}" > /app/version

# Copy root filesystem
COPY root/ /

# Create application and library directories
RUN mkdir -p /config /books /comics /files && \
    chown -R bsd:bsd /app/ubooquity /config /books /comics /files

# Set permissions
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* /healthz

ENV MAXMEM=512 \
    JAVA_OPTS=""

# --- Expose (Injected by Generator) ---
EXPOSE 2202 2203

# --- Volumes (Injected by Generator) ---
VOLUME /config /books /comics /files